package com.android.skip.utils

object Constants {
    const val FOREGROUND_ACCESSIBILITY_RECEIVER_ACTION = "SKIP_FOREGROUND_ACCESSIBILITY_RECEIVER_ACTION"

    const val FOREGROUND_ACCESSIBILITY_RECEIVER_ENABLED = "SKIP_FOREGROUND_ACCESSIBILITY_RECEIVER_ENABLED"

    const val SKIP_FOREGROUND_ACCESSIBILITY = "SKIP_FOREGROUND_ACCESSIBILITY"
}